/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vista.entrenador;

import com.abstracto.Usuario;
import com.entidades.Entrenador;
import com.entidades.Gimnasio;
import com.entidades.Sesion;
import java.awt.event.KeyEvent;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhona
 */
public class GestionarSesionesEntrenador extends javax.swing.JPanel {
    MenuEntrenador menuPadre;
    Gimnasio gymPrincipal;
    Entrenador entrenadorActivo;
    Map<String, Integer> ordenDias;
    DefaultTableModel modelo;
    int filaCambiar = -1;
    /**
     * Creates new form GestionarSesionesEntrenador
     */
    public GestionarSesionesEntrenador(MenuEntrenador menuEntrenador, Gimnasio principal, Entrenador entrenador) {
        initComponents();
        menuPadre = menuEntrenador;
        gymPrincipal = principal;
        entrenadorActivo = entrenador;
        
        ordenDias = new HashMap<>();
        modelo = (DefaultTableModel) tblSesiones.getModel();
        
        ordenDias.put("lunes", 1);
        ordenDias.put("martes", 2);
        ordenDias.put("miercoles", 3);
        ordenDias.put("jueves", 4);
        ordenDias.put("viernes", 5);
        ordenDias.put("sabado", 6);
        
        actualizarSesiones();
        tblSesiones.repaint();
    }
    
    public void actualizarSesiones(){
        List<Sesion> sesiones = entrenadorActivo.getSesiones();
        sesiones.sort(Comparator.comparingInt(s -> ordenDias.get(s.getDia().toLowerCase())));
        modelo.setNumRows(0);
        for (Sesion sesion : sesiones) {
                modelo.addRow(new Object[]{sesion.getDia(), sesion.getNombre(), sesion.getHoraIni() + "-" + sesion.getHoraFin(), sesion.getCodigo()});
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSesiones = new javax.swing.JTable();
        btnCrearNuevaSesion = new javax.swing.JButton();
        btnEliminarSesion = new javax.swing.JButton();
        btnDetallesSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarSesion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(77, 77, 77));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Dia", "Nombre", "Hora", "Código"
            }
        ));
        jScrollPane1.setViewportView(tblSesiones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 207, 480, 260));

        btnCrearNuevaSesion.setText("Crear una nueva sesión");
        btnCrearNuevaSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearNuevaSesionActionPerformed(evt);
            }
        });
        add(btnCrearNuevaSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 160, -1));

        btnEliminarSesion.setText("Eliminar sesión");
        btnEliminarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarSesionActionPerformed(evt);
            }
        });
        add(btnEliminarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 160, -1));

        btnDetallesSesion.setText("Detalles de la sesión");
        btnDetallesSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesSesionActionPerformed(evt);
            }
        });
        add(btnDetallesSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar una sesión (nombre o código):");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, -1, -1));

        txtBuscarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarSesionActionPerformed(evt);
            }
        });
        txtBuscarSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarSesionKeyPressed(evt);
            }
        });
        add(txtBuscarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 200, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/gestionSesiones.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearNuevaSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearNuevaSesionActionPerformed
        CrearSesión crearSesion = new CrearSesión(this, entrenadorActivo, gymPrincipal);
        crearSesion.setVisible(true);
    }//GEN-LAST:event_btnCrearNuevaSesionActionPerformed

    private void btnEliminarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarSesionActionPerformed
        filaCambiar = tblSesiones.getSelectedRow();
        if(filaCambiar != -1){
            int codigoSesion = (int) tblSesiones.getValueAt(filaCambiar, 3);
            int opcion = JOptionPane.showConfirmDialog(this, "LA SESIÓN SE ELIMINARA DE FORMA PERMANENTE, DESEA CONTINUAR?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if(opcion == JOptionPane.YES_OPTION){
                gymPrincipal.eliminarSesionCodigo(codigoSesion);
                entrenadorActivo.eliminarSesion(codigoSesion);
                modelo.removeRow(filaCambiar);
                JOptionPane.showMessageDialog(this, "SESIÓN ELIMINADA CON EXITO");
                actualizarSesiones();
                tblSesiones.repaint();
            }
        }
    }//GEN-LAST:event_btnEliminarSesionActionPerformed

    private void btnDetallesSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesSesionActionPerformed
        filaCambiar = tblSesiones.getSelectedRow();
        if(filaCambiar != -1){
            int codigoSesion = Integer.parseInt(tblSesiones.getValueAt(filaCambiar, 3).toString());
            List<Sesion> sesiones = gymPrincipal.getSesiones();
            for(Sesion sesion : sesiones){
                if(sesion.getCodigo()==codigoSesion){
                    JOptionPane.showMessageDialog(this, "Integrantes: " + "\n" + sesion.listarNombreIntegrantes() + "\n" + "Cantidad de integrantes: " + sesion.getIntegrantes().size());
                }
            }
        }
    }//GEN-LAST:event_btnDetallesSesionActionPerformed

    private void txtBuscarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarSesionActionPerformed
        
    }//GEN-LAST:event_txtBuscarSesionActionPerformed

    private void txtBuscarSesionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarSesionKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!txtBuscarSesion.getText().isBlank() || txtBuscarSesion.getText().isEmpty()){
                String buscarString = (String) txtBuscarSesion.getText();
                if(buscarString.replace(" ", "").matches("[a-zA-Z]+")){
                    if(gymPrincipal.buscarSesionNombre(buscarString)){
                        for(int i = 0; i<modelo.getRowCount(); i++){
                            if(((String) modelo.getValueAt(i, 1)).equalsIgnoreCase(buscarString)){
                                tblSesiones.setRowSelectionInterval(i, i);
                                txtBuscarSesion.setText("");
                                break;
                            }
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "No se encontro una sesión con ese nombre"); 
                    }
                }
                else if(buscarString.matches("\\d+")){
                    int buscarInt = Integer.parseInt(buscarString);
                    if(gymPrincipal.buscarSesionCodigo(buscarInt)){
                        for(int i = 0; i<modelo.getRowCount(); i++){
                            if((int) modelo.getValueAt(i, 3) == buscarInt){
                                tblSesiones.setRowSelectionInterval(i, i);
                                txtBuscarSesion.setText("");
                                break;
                            }
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "No se encontro una sesión con ese código"); 
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Debe buscar un código o un nombre!", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_txtBuscarSesionKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearNuevaSesion;
    private javax.swing.JButton btnDetallesSesion;
    private javax.swing.JButton btnEliminarSesion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSesiones;
    private javax.swing.JTextField txtBuscarSesion;
    // End of variables declaration//GEN-END:variables
}
