/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vista.entrenador;

import com.abstracto.Usuario;
import com.entidades.Gimnasio;

/**
 *
 * @author jhona
 */
public class InicioEntrenador extends javax.swing.JPanel {
    MenuEntrenador menuPadre;
    Gimnasio gymPrincipal;
    Usuario usuarioActivo;
    /**
     * Creates new form InicioEntrenador
     */
    public InicioEntrenador(MenuEntrenador menuEntrenador, Gimnasio gimnasio, Usuario usuario) {
        initComponents();
        menuPadre = menuEntrenador;
        gymPrincipal = gimnasio;
        usuarioActivo = usuario;
        if(usuario.getGenero().equalsIgnoreCase("Hombre")){
           lblBienvenido.setText("Bienvenido " + usuario.getNombre() + "!");
        }
        else{
           lblBienvenido.setText("Bienvenida " + usuario.getNombre() + "!"); 
        }
        lblCorreo.setText(usuario.getCorreo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBienvenido = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setText("jLabel1");
        add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        lblCorreo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCorreo.setForeground(new java.awt.Color(204, 204, 255));
        lblCorreo.setText("jLabel2");
        add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/gymrexInicio2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblCorreo;
    // End of variables declaration//GEN-END:variables
}
