/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vista.entrenador;

import com.abstracto.Usuario;
import com.entidades.Entrenador;
import com.entidades.Gimnasio;
import com.vista.Ayuda;
import com.vista.MenuPrincipal;
import com.vista.cliente.VerNotificaciones;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author jhona
 */
public class MenuEntrenador extends javax.swing.JPanel {
    MenuPrincipal menuPadre;
    Gimnasio gymPrincipal;
    Usuario usuarioActivo;
    InicioEntrenador inicioEntrenador;
    GestionarSesionesEntrenador gestionarSesiones;
    VerEstadisticas verEstadisticas;
    VerNotificaciones verNotificaciones;
    /**
     * Creates new form MenuEntrenador
     */
    public MenuEntrenador(MenuPrincipal menuPrincipal, Gimnasio principal, Usuario usuario) {
        initComponents();
        menuPadre = menuPrincipal;
        gymPrincipal = principal;
        usuarioActivo = usuario;
        inicioEntrenador = new InicioEntrenador(this, principal, usuario);
        gestionarSesiones = new GestionarSesionesEntrenador(this, principal,(Entrenador) usuario);
        verEstadisticas = new VerEstadisticas(this, principal, usuario);
        verNotificaciones = new VerNotificaciones(this, principal, usuario);
        actualizarContenidoMenu(inicioEntrenador);
    }
    
    public void actualizarContenidoMenu(JPanel x){
        x.setSize(544, 500);
        x.setLocation(0, 0);
        
        contenidoMenu.removeAll();
        contenidoMenu.add(x, BorderLayout.CENTER);
        contenidoMenu.revalidate();
        contenidoMenu.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenidoMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnGestionarSesiones = new javax.swing.JButton();
        btnVerEstadisticas = new javax.swing.JButton();
        btnGestionarNotificaciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();

        setBackground(new java.awt.Color(75, 100, 178));

        contenidoMenu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoMenuLayout = new javax.swing.GroupLayout(contenidoMenu);
        contenidoMenu.setLayout(contenidoMenuLayout);
        contenidoMenuLayout.setHorizontalGroup(
            contenidoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        contenidoMenuLayout.setVerticalGroup(
            contenidoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 51, 153));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnGestionarSesiones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGestionarSesiones.setForeground(new java.awt.Color(0, 51, 153));
        btnGestionarSesiones.setText("Gestionar sesiones");
        btnGestionarSesiones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGestionarSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarSesionesActionPerformed(evt);
            }
        });

        btnVerEstadisticas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerEstadisticas.setForeground(new java.awt.Color(0, 51, 153));
        btnVerEstadisticas.setText("Ver estadisticas");
        btnVerEstadisticas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerEstadisticasActionPerformed(evt);
            }
        });

        btnGestionarNotificaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGestionarNotificaciones.setForeground(new java.awt.Color(0, 51, 153));
        btnGestionarNotificaciones.setText("Gestionar notificaciones");
        btnGestionarNotificaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGestionarNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarNotificacionesActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 51, 153));
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAyuda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAyuda.setForeground(new java.awt.Color(0, 51, 153));
        btnAyuda.setText("Ayuda");
        btnAyuda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(btnGestionarSesiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerEstadisticas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarNotificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnInicio)
                .addGap(39, 39, 39)
                .addComponent(btnGestionarSesiones)
                .addGap(39, 39, 39)
                .addComponent(btnVerEstadisticas)
                .addGap(39, 39, 39)
                .addComponent(btnGestionarNotificaciones)
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnAyuda))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenidoMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenidoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        actualizarContenidoMenu(inicioEntrenador);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnGestionarSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarSesionesActionPerformed
        actualizarContenidoMenu(gestionarSesiones);
    }//GEN-LAST:event_btnGestionarSesionesActionPerformed

    private void btnVerEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerEstadisticasActionPerformed
        actualizarContenidoMenu(verEstadisticas);
    }//GEN-LAST:event_btnVerEstadisticasActionPerformed

    private void btnGestionarNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarNotificacionesActionPerformed
        actualizarContenidoMenu(verNotificaciones);
    }//GEN-LAST:event_btnGestionarNotificacionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        menuPadre.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Ayuda menuAyuda = new Ayuda();
        menuAyuda.setVisible(true);
    }//GEN-LAST:event_btnAyudaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnGestionarNotificaciones;
    private javax.swing.JButton btnGestionarSesiones;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerEstadisticas;
    private javax.swing.JPanel contenidoMenu;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
