/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vista.entrenador;

import com.abstracto.Usuario;
import com.entidades.Gimnasio;

/**
 *
 * @author jhona
 */
public class VerEstadisticas extends javax.swing.JPanel {
    MenuEntrenador menuPadre;
    Gimnasio gymPrincipal;
    Usuario usuarioActivo;
    /**
     * Creates new form VerEstadisticas
     */
    public VerEstadisticas(MenuEntrenador menuEntrenador, Gimnasio gimnasio, Usuario usuario) {
        initComponents();
        menuPadre = menuEntrenador;
        gymPrincipal = gimnasio;
        usuarioActivo = usuario;
        labelCantUsuarios.setText(""+gymPrincipal.getUsuarios().size());
        labelCantidadSesiones.setText(""+gymPrincipal.getSesiones().size());
        labelIngresos.setText(gymPrincipal.obtenerIngresos()+"$");
        labelMembresiasActivas.setText(""+gymPrincipal.cantidadMembresiasActivas());
        labelMembresiasAnuales.setText(gymPrincipal.porcentajeMembresiasAnuales()+"%");
        labelMembresiasMensuales.setText(gymPrincipal.porcentajeMembresiasMensuales()+"%");
        labelMembresiasTrimestrales.setText(gymPrincipal.porcentajeMembresiasTrimestrales()+"%");
        labelPorcentajeEstudiantes.setText(gymPrincipal.calcularPorcentajeEstudiantes()+"%");
        labelPorcentajeHombres.setText(gymPrincipal.calcularPorcentajeHombres()+"%");
        labelPorcentajeMujeres.setText(gymPrincipal.calcularPorcentajeMujeres()+"%");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelCantUsuarios = new javax.swing.JLabel();
        labelPorcentajeHombres = new javax.swing.JLabel();
        labelPorcentajeMujeres = new javax.swing.JLabel();
        labelPorcentajeEstudiantes = new javax.swing.JLabel();
        labelIngresos = new javax.swing.JLabel();
        labelMembresiasActivas = new javax.swing.JLabel();
        labelMembresiasMensuales = new javax.swing.JLabel();
        labelMembresiasTrimestrales = new javax.swing.JLabel();
        labelMembresiasAnuales = new javax.swing.JLabel();
        labelCantidadSesiones = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(77, 77, 77));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Estadisticas de Gym Rex");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("Cantidad de usuarios:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 35, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Porcentaje de hombres:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 79, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("Porcentaje de mujeres:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 123, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Porcentaje de estudiantes");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 167, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Ingresos totales:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 211, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 153));
        jLabel7.setText("Membresías activas:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 35, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 153));
        jLabel8.setText("%Membresías mensuales:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 79, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 153));
        jLabel9.setText("%Membresías trimestrales:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 123, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 51, 153));
        jLabel10.setText("%Membresías anuales:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 167, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 153));
        jLabel11.setText("Cantidad de sesiones:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 211, -1, -1));

        labelCantUsuarios.setForeground(new java.awt.Color(51, 51, 51));
        labelCantUsuarios.setText("jLabel12");
        jPanel1.add(labelCantUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 35, -1, -1));

        labelPorcentajeHombres.setForeground(new java.awt.Color(51, 51, 51));
        labelPorcentajeHombres.setText("jLabel12");
        jPanel1.add(labelPorcentajeHombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 79, -1, -1));

        labelPorcentajeMujeres.setForeground(new java.awt.Color(51, 51, 51));
        labelPorcentajeMujeres.setText("jLabel13");
        jPanel1.add(labelPorcentajeMujeres, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 123, -1, -1));

        labelPorcentajeEstudiantes.setForeground(new java.awt.Color(51, 51, 51));
        labelPorcentajeEstudiantes.setText("jLabel14");
        jPanel1.add(labelPorcentajeEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 167, -1, -1));

        labelIngresos.setForeground(new java.awt.Color(51, 51, 51));
        labelIngresos.setText("jLabel15");
        jPanel1.add(labelIngresos, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 211, -1, -1));

        labelMembresiasActivas.setForeground(new java.awt.Color(51, 51, 51));
        labelMembresiasActivas.setText("jLabel16");
        jPanel1.add(labelMembresiasActivas, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 35, -1, -1));

        labelMembresiasMensuales.setForeground(new java.awt.Color(51, 51, 51));
        labelMembresiasMensuales.setText("jLabel17");
        jPanel1.add(labelMembresiasMensuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(399, 79, -1, -1));

        labelMembresiasTrimestrales.setForeground(new java.awt.Color(51, 51, 51));
        labelMembresiasTrimestrales.setText("jLabel18");
        jPanel1.add(labelMembresiasTrimestrales, new org.netbeans.lib.awtextra.AbsoluteConstraints(408, 123, -1, -1));

        labelMembresiasAnuales.setForeground(new java.awt.Color(51, 51, 51));
        labelMembresiasAnuales.setText("jLabel19");
        jPanel1.add(labelMembresiasAnuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 167, -1, -1));

        labelCantidadSesiones.setForeground(new java.awt.Color(51, 51, 51));
        labelCantidadSesiones.setText("jLabel20");
        jPanel1.add(labelCantidadSesiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 211, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 181, 480, 290));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/estadisticas.png"))); // NOI18N
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -100, 570, 700));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCantUsuarios;
    private javax.swing.JLabel labelCantidadSesiones;
    private javax.swing.JLabel labelIngresos;
    private javax.swing.JLabel labelMembresiasActivas;
    private javax.swing.JLabel labelMembresiasAnuales;
    private javax.swing.JLabel labelMembresiasMensuales;
    private javax.swing.JLabel labelMembresiasTrimestrales;
    private javax.swing.JLabel labelPorcentajeEstudiantes;
    private javax.swing.JLabel labelPorcentajeHombres;
    private javax.swing.JLabel labelPorcentajeMujeres;
    // End of variables declaration//GEN-END:variables
}
