/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vista.cliente;

import com.abstracto.Usuario;
import com.entidades.Cliente;
import com.entidades.Gimnasio;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author jhona
 */
public class GestionMembresia extends javax.swing.JPanel {
    MenuCliente menuPadre;
    Gimnasio gymPrincipal;
    Usuario usuarioActivo;
    SubMenuVerMembresia subMenuVer;
    SubMenuComprarMembresia subMenuComprar;
    /**
     * Creates new form gestionMembresia
     */
    public GestionMembresia(MenuCliente menuCliente, Gimnasio principal, Usuario usuario) {
        initComponents();
        menuPadre = menuCliente;
        gymPrincipal = principal;
        usuarioActivo = usuario;
        subMenuComprar = new SubMenuComprarMembresia(this, principal, usuario);
        if(usuario instanceof Cliente cliente){
            if(cliente.getMembresia() != null){
                cliente.getMembresia().establecerEstado();
                if(cliente.getMembresia().isEstado()){
                    subMenuVer = new SubMenuVerMembresia(this, principal, usuario);
                    cambiarPanel(subMenuVer);
                }
                else{
                    cambiarPanel(subMenuComprar);
                }
            }
            else{
                cambiarPanel(subMenuComprar);
            }
        }
    }
    
    public void cambiarPanel(JPanel x){
        x.setSize(500, 343);
        x.setLocation(0, 0);
        
        contenidoMembresia.removeAll();
        contenidoMembresia.add(x, BorderLayout.CENTER);
        contenidoMembresia.revalidate();
        contenidoMembresia.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMembresia = new javax.swing.JLabel();
        contenidoMembresia = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(77, 77, 77));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMembresia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblMembresia.setForeground(new java.awt.Color(255, 255, 255));
        lblMembresia.setText("Administre o compre una membresía");
        lblMembresia.setAlignmentX(0.5F);
        add(lblMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 57, -1, -1));

        contenidoMembresia.setBackground(new java.awt.Color(255, 255, 255));
        contenidoMembresia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3));

        javax.swing.GroupLayout contenidoMembresiaLayout = new javax.swing.GroupLayout(contenidoMembresia);
        contenidoMembresia.setLayout(contenidoMembresiaLayout);
        contenidoMembresiaLayout.setHorizontalGroup(
            contenidoMembresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
        );
        contenidoMembresiaLayout.setVerticalGroup(
            contenidoMembresiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        add(contenidoMembresia, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 134, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/imagenmembresia.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenidoMembresia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblMembresia;
    // End of variables declaration//GEN-END:variables
}
