/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vista.cliente;

import com.abstracto.Usuario;
import com.entidades.Cliente;
import com.entidades.Gimnasio;
import com.entidades.Sesion;
import java.awt.event.KeyEvent;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jhona
 */
public class GestionSesiones extends javax.swing.JPanel {
    MenuCliente menuPadre;
    Gimnasio gymPrincipal;
    Usuario usuarioActivo;
    Map<String, Integer> ordenDias;
    DefaultTableModel modelo;
    int filaCambiar = -1;
    /**
     * Creates new form GestionSesiones
     */
    public GestionSesiones(MenuCliente menuCliente, Gimnasio principal, Usuario usuario) {
        initComponents();
        menuPadre = menuCliente;
        gymPrincipal = principal;
        usuarioActivo = usuario;
        
        ordenDias = new HashMap<>();
        modelo = (DefaultTableModel) tblSesiones.getModel();
        
        ordenDias.put("lunes", 1);
        ordenDias.put("martes", 2);
        ordenDias.put("miercoles", 3);
        ordenDias.put("jueves", 4);
        ordenDias.put("viernes", 5);
        ordenDias.put("sabado", 6);
        
        actualizarSesiones();
        tblSesiones.repaint();
    }
    
    
    
    public void actualizarSesiones(){
        List<Sesion> sesiones = gymPrincipal.getSesiones();
        sesiones.sort(Comparator.comparingInt(s -> ordenDias.get(s.getDia().toLowerCase())));
        modelo.setNumRows(0);
        for (Sesion sesion : sesiones) {
            if(sesion.buscarIntegrante(usuarioActivo.getCedula())){
                modelo.addRow(new Object[]{sesion.getDia(), sesion.getNombre(), sesion.getHoraIni() + "-" + sesion.getHoraFin(), sesion.getCodigo(), "Si"});
            }
            else{
                modelo.addRow(new Object[]{sesion.getDia(), sesion.getNombre(), sesion.getHoraIni() + "-" + sesion.getHoraFin(), sesion.getCodigo(), "No"});
            }
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInscribirse = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBuscarSesion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSesiones = new javax.swing.JTable();
        btnDetallesSesion = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(77, 77, 77));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnInscribirse.setText("Inscribirse a la sesión");
        btnInscribirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInscribirseActionPerformed(evt);
            }
        });
        add(btnInscribirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, -1));

        btnEliminar.setText("Eliminar inscripción");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 150, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscar una sesión (nombre o código):");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 56, -1, 30));

        txtBuscarSesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBuscarSesionKeyPressed(evt);
            }
        });
        add(txtBuscarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 200, -1));

        jScrollPane1.setRowHeaderView(null);

        tblSesiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dia", "Nombre", "Hora", "Código", "Inscrito"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSesiones.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblSesiones);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 199, 481, 271));

        btnDetallesSesion.setText("Detalles de la sesión");
        btnDetallesSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesSesionActionPerformed(evt);
            }
        });
        add(btnDetallesSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 150, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/gestionSesionesCliente.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnInscribirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInscribirseActionPerformed
        filaCambiar = tblSesiones.getSelectedRow();
        if(filaCambiar != -1){
            int codigoSesion = Integer.parseInt(tblSesiones.getValueAt(filaCambiar, 3).toString());
            List<Sesion> sesiones = gymPrincipal.getSesiones();
            for (Sesion sesion : sesiones) {
                if(sesion.getCodigo()==codigoSesion){
                    if(!sesion.buscarIntegrante(usuarioActivo.getCedula())){
                        sesion.insertarIntegrante((Cliente)usuarioActivo);
                        JOptionPane.showMessageDialog(this, "Se ha inscrito a la sesión con exito!");
                        modelo.setValueAt("Si", filaCambiar, 4);
                        tblSesiones.repaint();
                        break;
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Usted ya esta inscrito en esta sesión!");
                    }
                }
            }
        }
        
    }//GEN-LAST:event_btnInscribirseActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        filaCambiar = tblSesiones.getSelectedRow();
        if(filaCambiar != -1){
            int codigoSesion = Integer.parseInt(tblSesiones.getValueAt(filaCambiar, 3).toString());
            List<Sesion> sesiones = gymPrincipal.getSesiones();
            for (Sesion sesion : sesiones) {
                if(sesion.getCodigo()==codigoSesion){
                    if(sesion.buscarIntegrante(usuarioActivo.getCedula())){
                        sesion.eliminarIntegrante(usuarioActivo.getCedula());
                        JOptionPane.showMessageDialog(this, "Se ha eliminado la inscripción a la sesión con exito!");
                        modelo.setValueAt("No", filaCambiar, 4);
                        tblSesiones.repaint();
                        break;
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Usted no esta inscrito en esta sesión!");
                    }
                }
            } 
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnDetallesSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesSesionActionPerformed
        filaCambiar = tblSesiones.getSelectedRow();
        if(filaCambiar != -1){
            int codigoSesion = Integer.parseInt(tblSesiones.getValueAt(filaCambiar, 3).toString());
            List<Sesion> sesiones = gymPrincipal.getSesiones();
            for(Sesion sesion : sesiones){
                if(sesion.getCodigo()==codigoSesion){
                    JOptionPane.showMessageDialog(this, "Entrenador: " + sesion.getEntrenador().getNombre() + "\n" + "Integrantes: " + "\n" + sesion.listarNombreIntegrantes());
                }
            }
        }
    }//GEN-LAST:event_btnDetallesSesionActionPerformed

    private void txtBuscarSesionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarSesionKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            if(!txtBuscarSesion.getText().isBlank() || txtBuscarSesion.getText().isEmpty()){
                String buscarString = (String) txtBuscarSesion.getText();
                if(buscarString.replace(" ", "").matches("[a-zA-Z]+")){
                    if(gymPrincipal.buscarSesionNombre(buscarString)){
                        for(int i = 0; i<modelo.getRowCount(); i++){
                            if(((String) modelo.getValueAt(i, 1)).equalsIgnoreCase(buscarString)){
                                tblSesiones.setRowSelectionInterval(i, i);
                                txtBuscarSesion.setText("");
                                break;
                            }
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "No se encontro una sesión con ese nombre"); 
                    }
                }
                else if(buscarString.matches("\\d+")){
                    int buscarInt = Integer.parseInt(buscarString);
                    if(gymPrincipal.buscarSesionCodigo(buscarInt)){
                        for(int i = 0; i<modelo.getRowCount(); i++){
                            if((int) modelo.getValueAt(i, 3) == buscarInt){
                                tblSesiones.setRowSelectionInterval(i, i);
                                txtBuscarSesion.setText("");
                                break;
                            }
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "No se encontro una sesión con ese código"); 
                    }
                }
                else{
                    JOptionPane.showMessageDialog(this, "Debe buscar un código o un nombre!", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_txtBuscarSesionKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetallesSesion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInscribirse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSesiones;
    private javax.swing.JTextField txtBuscarSesion;
    // End of variables declaration//GEN-END:variables
}
