/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vista.cliente;

import com.abstracto.Usuario;
import com.entidades.Gimnasio;
import com.vista.Ayuda;
import com.vista.MenuPrincipal;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author jhona
 */
public class MenuCliente extends javax.swing.JPanel {
    MenuPrincipal menuPadre;
    Gimnasio gymPrincipal;
    Usuario usuarioActivo;
    InicioCliente inicioCliente;
    GestionMembresia gestionMembresia;
    GestionSesiones gestionarSesiones;
    VerNotificaciones verNotificaciones;
    
    /**
     * Creates new form MenuCliente
     */
    public MenuCliente(MenuPrincipal menuPrincipal, Gimnasio principal, Usuario usuario) {
        initComponents();
        menuPadre = menuPrincipal;
        gymPrincipal = principal;
        usuarioActivo = usuario;
        inicioCliente = new InicioCliente(this, principal, usuario);
        gestionMembresia = new GestionMembresia(this, principal, usuario);
        gestionarSesiones = new GestionSesiones(this, principal, usuario);
        verNotificaciones = new VerNotificaciones(this, principal, usuario);
        actualizarContenidoMenu(inicioCliente);
    }
    
    public void actualizarContenidoMenu(JPanel x){
        x.setSize(544, 500);
        x.setLocation(0, 0);
        
        contenidoMenu.removeAll();
        contenidoMenu.add(x, BorderLayout.CENTER);
        contenidoMenu.revalidate();
        contenidoMenu.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnGestionarMembresia = new javax.swing.JButton();
        btnGestionarSesiones = new javax.swing.JButton();
        btnVerNotificaciones = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        contenidoMenu = new javax.swing.JPanel();

        setBackground(new java.awt.Color(75, 100, 178));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInicio.setForeground(new java.awt.Color(0, 51, 153));
        btnInicio.setText("Inicio");
        btnInicio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btnGestionarMembresia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGestionarMembresia.setForeground(new java.awt.Color(0, 51, 153));
        btnGestionarMembresia.setText("Gestionar membresía");
        btnGestionarMembresia.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGestionarMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarMembresiaActionPerformed(evt);
            }
        });

        btnGestionarSesiones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGestionarSesiones.setForeground(new java.awt.Color(0, 51, 153));
        btnGestionarSesiones.setText("Gestionar sesiones");
        btnGestionarSesiones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGestionarSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarSesionesActionPerformed(evt);
            }
        });

        btnVerNotificaciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVerNotificaciones.setForeground(new java.awt.Color(0, 51, 153));
        btnVerNotificaciones.setText("Ver notificaciones");
        btnVerNotificaciones.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnVerNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerNotificacionesActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(0, 51, 153));
        btnSalir.setText("Salir");
        btnSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnAyuda.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAyuda.setForeground(new java.awt.Color(0, 51, 153));
        btnAyuda.setText("Ayuda");
        btnAyuda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVerNotificaciones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarSesiones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGestionarMembresia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAyuda, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnInicio)
                .addGap(39, 39, 39)
                .addComponent(btnGestionarMembresia)
                .addGap(39, 39, 39)
                .addComponent(btnGestionarSesiones)
                .addGap(39, 39, 39)
                .addComponent(btnVerNotificaciones)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnAyuda))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        contenidoMenu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoMenuLayout = new javax.swing.GroupLayout(contenidoMenu);
        contenidoMenu.setLayout(contenidoMenuLayout);
        contenidoMenuLayout.setHorizontalGroup(
            contenidoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        contenidoMenuLayout.setVerticalGroup(
            contenidoMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenidoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contenidoMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        actualizarContenidoMenu(inicioCliente);
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnGestionarMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarMembresiaActionPerformed
        actualizarContenidoMenu(gestionMembresia);
    }//GEN-LAST:event_btnGestionarMembresiaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        menuPadre.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGestionarSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarSesionesActionPerformed
        actualizarContenidoMenu(gestionarSesiones);
    }//GEN-LAST:event_btnGestionarSesionesActionPerformed

    private void btnVerNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerNotificacionesActionPerformed
        actualizarContenidoMenu(verNotificaciones);
    }//GEN-LAST:event_btnVerNotificacionesActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        Ayuda menuAyuda = new Ayuda();
        menuAyuda.setVisible(true);
    }//GEN-LAST:event_btnAyudaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnGestionarMembresia;
    private javax.swing.JButton btnGestionarSesiones;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVerNotificaciones;
    private javax.swing.JPanel contenidoMenu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
