/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vista.cliente;

import com.abstracto.Usuario;
import com.entidades.Cliente;
import com.entidades.Gimnasio;
import com.entidades.Membresia;
import javax.swing.JOptionPane;

/**
 *
 * @author jhona
 */
public class SubMenuVerMembresia extends javax.swing.JPanel {
    GestionMembresia menuPadre;
    Gimnasio gymPrincipal;
    Usuario usuarioActivo;
    Membresia membresia;
    float costoMembresia;
    /**
     * Creates new form SubMenuVerMembresia
     */
    public SubMenuVerMembresia(GestionMembresia gestionMembresia, Gimnasio principal, Usuario usuario) {
        initComponents();
        menuPadre = gestionMembresia;
        gymPrincipal = principal;
        usuarioActivo = usuario;
        if(usuario instanceof Cliente cliente){
            membresia = cliente.getMembresia();
            costoMembresia = cliente.totalPagar();
        }
        lblCodigoMembresia.setText(""+membresia.getCodigo());
        lblTipoMembresia.setText(membresia.getTipo());
        lblValorPagadoMembresia.setText(""+costoMembresia + "$");
        lblTiempoRestante.setText(""+membresia.calcularTiempoRestante() + " dias");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblCodigoMembresia = new javax.swing.JLabel();
        lblTipoMembresia = new javax.swing.JLabel();
        lblValorPagadoMembresia = new javax.swing.JLabel();
        lblTiempoRestante = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Código de la membresia:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Tipo de membresia:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Valor pagado:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Tiempo restante:");

        jButton1.setText("Cancelar Membresia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblCodigoMembresia.setText("jLabel5");

        lblTipoMembresia.setText("jLabel5");

        lblValorPagadoMembresia.setText("jLabel5");

        lblTiempoRestante.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTiempoRestante)
                    .addComponent(lblValorPagadoMembresia)
                    .addComponent(lblCodigoMembresia)
                    .addComponent(lblTipoMembresia))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(176, 176, 176))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCodigoMembresia))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblTipoMembresia))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblValorPagadoMembresia))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblTiempoRestante))
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int resultado = JOptionPane.showConfirmDialog(this, "Esta seguro de que quiere CANCELAR su membresia?", "ADVERTENCIA!", JOptionPane.YES_NO_OPTION);
        if(resultado == JOptionPane.YES_OPTION){
            if(usuarioActivo instanceof Cliente cliente){
                cliente.desactivarMembresia();
                menuPadre.cambiarPanel(menuPadre.subMenuComprar);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblCodigoMembresia;
    private javax.swing.JLabel lblTiempoRestante;
    private javax.swing.JLabel lblTipoMembresia;
    private javax.swing.JLabel lblValorPagadoMembresia;
    // End of variables declaration//GEN-END:variables
}
