/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.vista.cliente;

import com.abstracto.Usuario;
import com.entidades.Cliente;
import com.entidades.Gimnasio;
import com.entidades.Membresia;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author jhona
 */
public class SubMenuComprarMembresia extends javax.swing.JPanel {
    GestionMembresia menuPadre;
    Gimnasio gymPrincipal;
    Usuario usuarioActivo;
    Membresia membresia;
    float costoBase = 65000;
    /**
     * Creates new form SubMenuComprarMembresia
     */
    public SubMenuComprarMembresia(GestionMembresia gestionMembresia, Gimnasio principal, Usuario usuario) {
        initComponents();
        menuPadre = gestionMembresia;
        gymPrincipal = principal;
        usuarioActivo = usuario;
        membresia = new Membresia(0, "Mensual", costoBase, LocalDate.now());
        txtCostoSinDescuentos.setText(membresia.costoTotal()+"$");
        txtCostoBase.setText(costoBase+"$");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbTipoMembresia = new javax.swing.JComboBox<>();
        txtCostoBase = new javax.swing.JTextField();
        txtCostoSinDescuentos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 153), 3));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Hazte miembro de Gym Rex!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 102));
        jLabel2.setText("Elija el tipo de membresía:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("Tarifa base(mensual) actual:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Costo sin descuentos:");

        cmbTipoMembresia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mensual", "Trimestral", "Anual" }));
        cmbTipoMembresia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoMembresiaActionPerformed(evt);
            }
        });

        txtCostoBase.setEditable(false);

        txtCostoSinDescuentos.setEditable(false);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(207, 207, 207))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCostoBase)
                            .addComponent(cmbTipoMembresia, 0, 90, Short.MAX_VALUE)
                            .addComponent(txtCostoSinDescuentos)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbTipoMembresia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCostoBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCostoSinDescuentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipoMembresiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoMembresiaActionPerformed
        if(cmbTipoMembresia.getSelectedIndex()==0){
            membresia.setTipo("Mensual");
        }
        else if(cmbTipoMembresia.getSelectedIndex()==1){
            membresia.setTipo("Trimestral");
        }
        else if(cmbTipoMembresia.getSelectedIndex()==2){
            membresia.setTipo("Anual");
        }
        txtCostoSinDescuentos.setText(membresia.costoTotal()+"$");
    }//GEN-LAST:event_cmbTipoMembresiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int codigoMaximo = gymPrincipal.obtenerCodigoMaximoMembresias();
        String tipo = "";
        if(cmbTipoMembresia.getSelectedIndex()==0){
            tipo = "Mensual";
        }
        else if(cmbTipoMembresia.getSelectedIndex()==1){
            tipo = "Trimestral";
        }
        else if(cmbTipoMembresia.getSelectedIndex()==2){
            tipo = "Anual";
        }
        if(usuarioActivo instanceof Cliente cliente){
            cliente.añadirMembresia(codigoMaximo + 1, tipo, costoBase, LocalDate.now());
            JOptionPane.showMessageDialog(this, "Compra realizada con exito!");
            menuPadre.cambiarPanel(new SubMenuVerMembresia(menuPadre, gymPrincipal, usuarioActivo));
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTipoMembresia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtCostoBase;
    private javax.swing.JTextField txtCostoSinDescuentos;
    // End of variables declaration//GEN-END:variables
}
