
package com.vista;

import java.awt.Font;
import java.awt.Color;
import com.abstracto.Usuario;
import com.entidades.Gimnasio;
import javax.swing.JTextField;
import javax.swing.JOptionPane;



public class InicioSesion extends javax.swing.JPanel {
    Gimnasio gymPrincipal;
    MenuPrincipal menuPrincipal;
    MenuInicioSesion menuPadre;
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion(MenuInicioSesion menuInicioSesion,Gimnasio principal) {
        initComponents();
        gymPrincipal = principal;
        menuPadre = menuInicioSesion;
        
        //add style
        addPlaceStyle(txtCedulaInicio);
        addPlaceStyle(txtContraseñaInicio);
    }
    
    public void addPlaceStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black); // color
        
    }
    
    public void removePlace(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.black); // color
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCedulaInicio = new javax.swing.JTextField();
        btnIniciarSesion = new javax.swing.JButton();
        txtContraseñaInicio = new javax.swing.JPasswordField();

        setMinimumSize(new java.awt.Dimension(599, 400));
        setPreferredSize(new java.awt.Dimension(599, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtCedulaInicio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCedulaInicio.setText("Cedula");
        txtCedulaInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtCedulaInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCedulaInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaInicioFocusLost(evt);
            }
        });

        btnIniciarSesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIniciarSesion.setText("Iniciar sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });

        txtContraseñaInicio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtContraseñaInicio.setText("Pin");
        txtContraseñaInicio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtContraseñaInicio.setEchoChar('\u0000');
        txtContraseñaInicio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtContraseñaInicioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtContraseñaInicioFocusLost(evt);
            }
        });
        txtContraseñaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtContraseñaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(txtCedulaInicio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnIniciarSesion)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(txtCedulaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContraseñaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));
    }// </editor-fold>//GEN-END:initComponents

    private void txtContraseñaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaInicioActionPerformed

    private void txtContraseñaInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseñaInicioFocusLost
        // TODO add your handling code here:
        if (txtContraseñaInicio.getPassword().length == 0) {
            addPlaceStyle(txtContraseñaInicio);
            txtContraseñaInicio.setText("Pin");
            txtContraseñaInicio.setEchoChar((char) 0);
        }
    }//GEN-LAST:event_txtContraseñaInicioFocusLost

    private void txtContraseñaInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtContraseñaInicioFocusGained
        // TODO add your handling code here:

        if (txtContraseñaInicio.getText().equalsIgnoreCase("Pin")) {
            txtContraseñaInicio.setText("");
            txtContraseñaInicio.requestFocus();
            // set contraseña character
            txtContraseñaInicio.setEchoChar('•'); //◯ ● •
            // remove plaCe style
            removePlace(txtContraseñaInicio);
        }
    }//GEN-LAST:event_txtContraseñaInicioFocusGained

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed

        try {
            String cedula = txtCedulaInicio.getText();
            char[] contraseñaChars = txtContraseñaInicio.getPassword();
            int pin = Integer.parseInt(new String(contraseñaChars));
            if(gymPrincipal.buscarUsuario(cedula)){
                Usuario usuario = gymPrincipal.obtenerUsuario(cedula);
                if(usuario.getPin() == pin){
                    menuPrincipal =new MenuPrincipal(menuPadre,usuario, gymPrincipal);
                    menuPrincipal.setVisible(true);
                    menuPadre.setVisible(false);
                    txtCedulaInicio.setText("Cedula");
                    txtContraseñaInicio.setText("Pin");
                    addPlaceStyle(txtContraseñaInicio);
                    txtContraseñaInicio.setEchoChar((char) 0);
                }
                else{
                    JOptionPane.showMessageDialog(this, "PIN INCORRECTO!");
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "LOS DATOS NO SE ENCUENTRAN REGISTRADOS");
            }
        } catch (NumberFormatException ob) {
            JOptionPane.showMessageDialog(this, "DATOS MAL DIGITADOS");
            txtContraseñaInicio.grabFocus();
            txtContraseñaInicio.selectAll();
            txtCedulaInicio.grabFocus();
            txtCedulaInicio.selectAll();
        }

    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    private void txtCedulaInicioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaInicioFocusLost
        // TODO add your handling code here:
        if (txtCedulaInicio.getText().length() == 0) {
            //add  placeholder
            addPlaceStyle(txtCedulaInicio);
            txtCedulaInicio.setText("Cedula");
        }
    }//GEN-LAST:event_txtCedulaInicioFocusLost

    private void txtCedulaInicioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaInicioFocusGained
        // TODO add your handling code here:
        if (txtCedulaInicio.getText().equalsIgnoreCase("Cedula")) {
            txtCedulaInicio.setText(null);
            txtCedulaInicio.requestFocus();
            // remove style
            
        }
    }//GEN-LAST:event_txtCedulaInicioFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCedulaInicio;
    private javax.swing.JPasswordField txtContraseñaInicio;
    // End of variables declaration//GEN-END:variables
}
