
package com.vista;

import com.entidades.Gimnasio;
import com.persistencia.ArchiGym;
import java.awt.BorderLayout;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jhona
 */
public class MenuInicioSesion extends javax.swing.JFrame {
    private Gimnasio gymRex = new Gimnasio(102, "Gym Rex");
    InicioSesion inicioSesion;
    Registro registro;
    /**
     * Creates new form MenuRegistro
     */
    public MenuInicioSesion() {
        initComponents();
        cargarGimnasio();
        Image icono = new ImageIcon(getClass().getResource("/com/imagenes/iconoGymRex128.png")).getImage();
        setIconImage(icono);
        inicioSesion = new InicioSesion(this,gymRex);
        registro = new Registro(gymRex);
        cambiarPanelSesion(inicioSesion);
    }
    
    private void cambiarPanelSesion(JPanel x){
        x.setSize(599, 400);
        x.setLocation(0, 0);
        
        contenidoInicio.removeAll();
        contenidoInicio.add(x, BorderLayout.CENTER);
        contenidoInicio.revalidate();
        contenidoInicio.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnInicioSesion = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        contenidoInicio = new javax.swing.JPanel();
        btnFormatear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gym Rex");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(java.awt.Color.white);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        btnInicioSesion.setText("Inicio de sesión");
        btnInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioSesionActionPerformed(evt);
            }
        });

        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        contenidoInicio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout contenidoInicioLayout = new javax.swing.GroupLayout(contenidoInicio);
        contenidoInicio.setLayout(contenidoInicioLayout);
        contenidoInicioLayout.setHorizontalGroup(
            contenidoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidoInicioLayout.setVerticalGroup(
            contenidoInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        btnFormatear.setText("Formatear");
        btnFormatear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormatearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInicioSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 313, Short.MAX_VALUE)
                .addComponent(btnFormatear)
                .addContainerGap())
            .addComponent(contenidoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInicioSesion)
                    .addComponent(btnRegistro)
                    .addComponent(btnFormatear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenidoInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioSesionActionPerformed
        cambiarPanelSesion(inicioSesion);
    }//GEN-LAST:event_btnInicioSesionActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        cambiarPanelSesion(registro);
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            ArchiGym persistenciaGym = new ArchiGym();
            persistenciaGym.guardar(gymRex);
        } catch (IOException ex) {
            System.out.println("ERROR: EL ARCHIVO DEL GIMNASIO NO SE GUARDO CORRECTAMENTE");
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void btnFormatearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormatearActionPerformed
        File file = new File("gimnasio.obj");
        if(file.exists()){
            int opcion = JOptionPane.showConfirmDialog(this, "ESTA SEGURO DE FORMATEAR EL GIMNASIO? TODOS LOS DATOS SE PERDERAN", "Formateo", JOptionPane.YES_NO_OPTION);
            if(opcion == JOptionPane.YES_OPTION){
                if(file.delete()){
                    JOptionPane.showMessageDialog(this, "SE HA BORRADO EL ARCHIVO CON EXITO");
                }
                else{
                    JOptionPane.showMessageDialog(this, "NO SE PUDO BORRAR EL ARCHIVO");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "NO HAY DATOS QUE FORMATEAR");
        }
        
        gymRex = new Gimnasio(102, "Gym Rex");
        inicioSesion = new InicioSesion(this, gymRex);
        registro = new Registro(gymRex);
        cambiarPanelSesion(inicioSesion);
    }//GEN-LAST:event_btnFormatearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicioSesion().setVisible(true);
            }
        });
    }
    
    public void cargarGimnasio(){
        ArchiGym persistenciaGym = new ArchiGym();
        if(new File("gimnasio.obj").exists()){
            try {
                gymRex = persistenciaGym.cargar();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "NO SE PUDIERON CARGAR LOS DATOS DEL GIMNASIO");
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(this, "NO SE PUDIERON CARGAR LOS DATOS DEL GIMNASIO");
            }
        }
        else{
            gymRex = new Gimnasio(102, "Gym Rex");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormatear;
    private javax.swing.JButton btnInicioSesion;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JPanel contenidoInicio;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
