
package com.vista;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;

import com.abstracto.Usuario;
import com.entidades.Cliente;
import com.entidades.Gimnasio;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import com.entidades.Entrenador;
import java.util.logging.Logger;
import com.excepciones.PinException;
import com.excepciones.CorreoException;
import com.control.ControladorGimnasio;
import com.excepciones.CedulaException;
import com.excepciones.PasswordException;
import com.excepciones.UserExistsException;
import com.excepciones.SoloLetrasExceptión;
import com.excepciones.EmptyFieldException;
import com.excepciones.LongitudNoAdmitidaExceptión;

/**
 *
 * @author jhona
 */
public class Registro extends javax.swing.JPanel {
    Gimnasio gymPrincipal;
    ControladorGimnasio gymControl = new ControladorGimnasio();
    /**
     * Creates new form InicioSesion
     */
    public Registro(Gimnasio gimnasio) {
        initComponents();
        this.gymPrincipal = gimnasio;
        this.gymControl = gymControl;
        
        addPlaceStyle(txtNombreRegistro);
        addPlaceStyle(txtCedulaRegistro);
        addPlaceStyle(txtPinRegistro);
        addPlaceStyle(txtCorreoRegistro);
        
    }
    
    public void addPlaceStyle(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(font.PLAIN|Font.BOLD);
        textField.setFont(font);
        textField.setForeground(Color.black); // color
        
    }
    
    public void removePlace(JTextField textField){
        Font font = textField.getFont();
        font = font.deriveFont(font.ITALIC);
        textField.setFont(font);
        textField.setForeground(Color.black); // color
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonesGenero = new javax.swing.ButtonGroup();
        botonesEstudiante = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtCedulaRegistro = new javax.swing.JTextField();
        txtPinRegistro = new javax.swing.JTextField();
        txtNombreRegistro = new javax.swing.JTextField();
        txtCorreoRegistro = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        rdbtnHombre = new javax.swing.JRadioButton();
        rdbtnMujer = new javax.swing.JRadioButton();
        btnRegistrarse = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        labelEstudiante = new javax.swing.JLabel();
        rdbtnSi = new javax.swing.JRadioButton();
        rdbtnNo = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(400, 599));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txtCedulaRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCedulaRegistro.setText("Cedula");
        txtCedulaRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtCedulaRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCedulaRegistroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCedulaRegistroFocusLost(evt);
            }
        });
        txtCedulaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaRegistroActionPerformed(evt);
            }
        });

        txtPinRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPinRegistro.setText("Pin");
        txtPinRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtPinRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPinRegistroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPinRegistroFocusLost(evt);
            }
        });
        txtPinRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPinRegistroActionPerformed(evt);
            }
        });

        txtNombreRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtNombreRegistro.setText("Nombre");
        txtNombreRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNombreRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreRegistroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreRegistroFocusLost(evt);
            }
        });

        txtCorreoRegistro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCorreoRegistro.setText("Correo");
        txtCorreoRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtCorreoRegistro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCorreoRegistroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCorreoRegistroFocusLost(evt);
            }
        });
        txtCorreoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoRegistroActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 102));
        jLabel5.setText("Genero:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 102));
        jLabel6.setText("Tipo:");

        botonesGenero.add(rdbtnHombre);
        rdbtnHombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdbtnHombre.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnHombre.setText("Hombre");

        botonesGenero.add(rdbtnMujer);
        rdbtnMujer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rdbtnMujer.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnMujer.setText("Mujer");

        btnRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        cmbTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente", "Entrenador" }));
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });

        labelEstudiante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelEstudiante.setForeground(new java.awt.Color(0, 51, 102));
        labelEstudiante.setText("Estudiante:");

        botonesEstudiante.add(rdbtnSi);
        rdbtnSi.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnSi.setText("Si");

        botonesEstudiante.add(rdbtnNo);
        rdbtnNo.setForeground(new java.awt.Color(51, 51, 51));
        rdbtnNo.setText("No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtNombreRegistro)
                    .addComponent(txtCedulaRegistro)
                    .addComponent(txtCorreoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPinRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdbtnHombre)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnMujer)))
                .addGap(79, 79, 79))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnRegistrarse))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelEstudiante)
                        .addGap(21, 21, 21)
                        .addComponent(rdbtnSi)
                        .addGap(18, 18, 18)
                        .addComponent(rdbtnNo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPinRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(rdbtnHombre)
                    .addComponent(rdbtnMujer))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstudiante)
                    .addComponent(rdbtnSi)
                    .addComponent(rdbtnNo))
                .addGap(33, 33, 33)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
        
        try {
            
        String cedula = txtCedulaRegistro.getText();
        String correo = txtCorreoRegistro.getText();
        String nombre = txtNombreRegistro.getText();
        int pin = Integer.parseInt(txtPinRegistro.getText());
        String genero = "";
        
        Usuario usu = gymControl.usuarioABuscar(pin);
            if (usu != null) {
                throw new UserExistsException("YA EXISTE UN USUARIO CON ESTA CEDULA.\nREVISA EL NUMERO DIGITADO, O INICIA SESION");
            }
        
        if(rdbtnHombre.isSelected()){
            genero = "Hombre";
        }
        else if(rdbtnMujer.isSelected()){
            genero = "Mujer";
        }
        if(!gymControl.buscarUsuario(cedula, gymPrincipal)){
            Usuario nuevo;
            if(cmbTipo.getSelectedIndex() == 0){
                nuevo = new Cliente(cedula, nombre, correo, pin, genero, rdbtnSi.isSelected());
            }
            else{
                nuevo = new Entrenador(cedula, nombre, correo, pin, genero);
            }
            gymControl.agregarUsuario(gymPrincipal, nuevo);       
            JOptionPane.showMessageDialog(null, "REGISTRO EXITOSO.");
            txtCedulaRegistro.setText("Cedula");
            txtCorreoRegistro.setText("Correo");
            txtNombreRegistro.setText("Nombre");
            txtPinRegistro.setText("Pin");
            botonesEstudiante.clearSelection();
            botonesGenero.clearSelection();
            cmbTipo.setSelectedIndex(0);
        }
        else{
            JOptionPane.showMessageDialog(this, "LA CEDULA QUE INTENTA REGISTRAR YA ESTA EN USO.");
            txtCedulaRegistro.grabFocus();
            txtCedulaRegistro.selectAll(); 
        }
        
        }catch (CedulaException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
            txtCedulaRegistro.grabFocus();
            txtCedulaRegistro.selectAll();
        }catch (LongitudNoAdmitidaExceptión ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            txtNombreRegistro.grabFocus();
            txtNombreRegistro.selectAll();
        }catch (NumberFormatException ob) {
            
            if (txtCedulaRegistro.getText().matches("\\d+")) {
                JOptionPane.showMessageDialog(this, "PIN INCORRECTO.");
                txtPinRegistro.grabFocus();
                txtPinRegistro.selectAll();
            }else {
                JOptionPane.showMessageDialog(this, "DATOS MAL DIGITADOS."); 
                txtCedulaRegistro.grabFocus();
                txtCedulaRegistro.selectAll();
            }
        }catch (CorreoException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            txtCorreoRegistro.grabFocus();
            txtCorreoRegistro.selectAll();
        }catch (PasswordException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            txtPinRegistro.grabFocus();
            txtPinRegistro.selectAll();
        } catch (SoloLetrasExceptión ex) {    
            JOptionPane.showMessageDialog(this, ex.getMessage());
            txtNombreRegistro.grabFocus();
            txtNombreRegistro.selectAll();
        }catch (EmptyFieldException ex) { 
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }catch (PinException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            txtPinRegistro.grabFocus();
            txtPinRegistro.selectAll();
            
        }catch (UserExistsException ex) {
            Logger.getLogger(Registro.class.getName()).log(Level.SEVERE, null, ex);
        }
        /*
        catch (IDException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        txtCedulaRegistro.grabFocus();
        txtCedulaRegistro.selectAll();
         */  
        
    
          /*  
        catch (IDException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            txtCedulaRegistro.grabFocus();
            txtCedulaRegistro.selectAll();
           */ 
        
        
           
    
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        if(cmbTipo.getSelectedIndex()==0){
            labelEstudiante.setEnabled(true);
            rdbtnNo.setEnabled(true);
            rdbtnSi.setEnabled(true);
        }
        else{
            labelEstudiante.setEnabled(false);
            rdbtnNo.setEnabled(false);
            rdbtnSi.setEnabled(false);
            botonesEstudiante.clearSelection();
        }
    }//GEN-LAST:event_cmbTipoActionPerformed

    private void txtCorreoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoRegistroActionPerformed

    private void txtCedulaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaRegistroActionPerformed

    private void txtPinRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPinRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPinRegistroActionPerformed

    private void txtCedulaRegistroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaRegistroFocusGained
        // TODO add your handling code here:
        if (txtCedulaRegistro.getText().equalsIgnoreCase("Cedula")) {
            txtCedulaRegistro.setText(null);
            txtCedulaRegistro.requestFocus();
            // remove style
            
        }

    }//GEN-LAST:event_txtCedulaRegistroFocusGained

    private void txtNombreRegistroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreRegistroFocusGained
        // TODO add your handling code here:
        if (txtNombreRegistro.getText().equalsIgnoreCase("Nombre")) {
            txtNombreRegistro.setText(null);
            txtNombreRegistro.requestFocus();
            // remove style
            
        }
    }//GEN-LAST:event_txtNombreRegistroFocusGained

    private void txtCorreoRegistroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoRegistroFocusGained
        // TODO add your handling code here:
        if (txtCorreoRegistro.getText().equalsIgnoreCase("Correo")) {
            txtCorreoRegistro.setText(null);
            txtCorreoRegistro.requestFocus();
            // remove style
            
        }
    }//GEN-LAST:event_txtCorreoRegistroFocusGained

    private void txtPinRegistroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPinRegistroFocusGained
        // TODO add your handling code here:
        if (txtPinRegistro.getText().equalsIgnoreCase("Pin")) {
            txtPinRegistro.setText(null);
            txtPinRegistro.requestFocus();
            // remove style
            //removePlace(txtPinRegistro);
        }
    }//GEN-LAST:event_txtPinRegistroFocusGained

    private void txtCedulaRegistroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCedulaRegistroFocusLost
        // TODO add your handling code here:
        if (txtCedulaRegistro.getText().length() == 0) {
            //add  placeholder
            addPlaceStyle(txtCedulaRegistro);
            txtCedulaRegistro.setText("Cedula");
        }

    }//GEN-LAST:event_txtCedulaRegistroFocusLost

    private void txtNombreRegistroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreRegistroFocusLost
        // TODO add your handling code here:
        if (txtNombreRegistro.getText().length() == 0) {
            //add  placeholder
            addPlaceStyle(txtNombreRegistro);
            txtNombreRegistro.setText("Nombre");
        }

    }//GEN-LAST:event_txtNombreRegistroFocusLost

    private void txtCorreoRegistroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCorreoRegistroFocusLost
        // TODO add your handling code here:
        if (txtCorreoRegistro.getText().length() == 0) {
            //add  placeholder
            addPlaceStyle(txtCorreoRegistro);
            txtCorreoRegistro.setText("Correo");
        }

    }//GEN-LAST:event_txtCorreoRegistroFocusLost

    private void txtPinRegistroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPinRegistroFocusLost
        // TODO add your handling code here:
        if (txtPinRegistro.getText().length() == 0) {
            //add  placeholder
            addPlaceStyle(txtPinRegistro);
            txtPinRegistro.setText("Pin");
        }
    }//GEN-LAST:event_txtPinRegistroFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botonesEstudiante;
    private javax.swing.ButtonGroup botonesGenero;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEstudiante;
    private javax.swing.JRadioButton rdbtnHombre;
    private javax.swing.JRadioButton rdbtnMujer;
    private javax.swing.JRadioButton rdbtnNo;
    private javax.swing.JRadioButton rdbtnSi;
    private javax.swing.JTextField txtCedulaRegistro;
    private javax.swing.JTextField txtCorreoRegistro;
    private javax.swing.JTextField txtNombreRegistro;
    private javax.swing.JTextField txtPinRegistro;
    // End of variables declaration//GEN-END:variables
}
